name: Setup
description: Restore node_modules and cache, then run pnpm install

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
        node-version-file: '.nvmrc'
    - run: pnpm --version
      shell: bash
    - run: pnpm i --frozen-lockfile
      shell: bash
